### ISSUE TITLE
Key for the RS256 algorithm must be one of type CryptoKey or JSON Web Key. Received an instance of Uint8Array

### ISSUE THREAD

**Issue by Celtcoste** [awinogrodzki/next-firebase-auth-edge#292]
#### Description:

I’m encountering a `TypeError` when attempting to verify cookies using the `RS256` algorithm in a Next.js middleware. The error occurs when I pass `cookieSignatureKeys` to the `authMiddleware`.

#### Error Stack:
```
⨯ node_modules/next-firebase-auth-edge/node_modules/jose/dist/browser/lib/check_key_type.js (46:1) @ asymmetricTypeCheck
⨯ Key for the RS256 algorithm must be one of type CryptoKey or JSON Web Key. Received an instance of Uint8Array
  44 |     }
  45 |     if (!isKeyLike(key)) {
> 46 |         throw new TypeError(invalidKeyInput(alg, key, ...types, allowJwk ? 'JSON Web Key' : null));
     | ^
  47 |     }
  48 |     if (key.type === 'secret') {
  49 |         throw new TypeError(`${tag(key)} instances for asymmetric algorithms must not be of type "secret"`);
```

#### What I've tried:

1. Environment Setup:

- Next.js version: 15+
- next-firebase-auth-edge version: ^1.8.2
- Node.js version: 22.3.0
- Firebase version: 10.13.2

2. Troubleshooting Steps Taken:

- I tried different versions of next-firebase-auth-edge and jose.
- Redid the Firebase setup from scratch, ensuring all keys and configs are properly set.

3. Code:

```
import { authMiddleware } from "next-firebase-auth-edge";
import { clientConfig, serverConfig } from "./config";

export async function middleware(request: NextRequest) {
  try {
    return authMiddleware(request, {
      loginPath: "/api/login",
      logoutPath: "/api/logout",
      apiKey: clientConfig.apiKey,
      cookieName: serverConfig.cookieName,
      cookieSignatureKeys: serverConfig.cookieSignatureKeys,
      cookieSerializeOptions: serverConfig.cookieSerializeOptions,
      serviceAccount: serverConfig.serviceAccount,
    });
  } catch (error) {
    console.error("Middleware error:", error);
    return new Response("Internal Server Error", { status: 500 });
  }
}

export const config = {
  matcher: [
    // Exclude paths to avoid infinite loops
    "/((?!api/refresh-token|_next/static|_next/image|favicon.ico).*)",
  ],
};
```

#### npx next info:

```
❯ npx next info

Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 22.3.0
  npm: 10.8.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.4-canary.38 // Latest available version is detected (15.0.4-canary.38).
  eslint-config-next: 15.0.2
  react: 18.3.0
  react-dom: 18.3.0
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

#### Additional information:

- I generate the token using:
`getIdToken()`

- The cookie header I am getting:
```
{
  "alg": "RS256",
  "kid": "bd0ae14d28d16578b31c8be6c8fded34d5e1a1c1",
  "typ": "JWT"
}
```

- I am not using `enableMultipleCookies`

**Comment by awinogrodzki** [comment]
Hey @Celtcoste!

Thanks for all the details!

I've tried but failed to reproduce the issue on my side. Would it be possible for you to create a public repository with issue reproduction?

**Comment by awinogrodzki** [comment]
Hey @Celtcoste!

Thanks for getting back on the topic.

This issue is reported from time to time and I was expecting it to be connected with native firebase cookie being used together with `next-firebase-auth-edge`. I will try to re-throw the error with more descriptive message of what's happening. 

Thanks for the feedback!

Cheers

**Comment by dperolio** [comment]
@awinogrodzki I'm running into this... I feel like I've tried everything. I don't understand what the issue is, can you explain it to me please, and how to fix?

**Comment by kcordoc** [comment]
I tried the solutions mentioned on other threads. However, none of those worked for me. Interestingly, I have an app deployed with this repo and that works fine. I tried to use the same setup and I haven't had any luck. I am not a developer and so I don't have the vocabulary to understand the solutions. However, I willing to try things as needed. 

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:06:57 PDT 2024; root:xnu-11215.41.3~3/RELEASE_ARM64_T6041
  Available memory (MB): 24576
  Available CPU cores: 12
Binaries:
  Node: 22.13.1
  npm: 10.9.2
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 15.1.4 // There is a newer version (15.1.5) available, upgrade recommended! 
  eslint-config-next: 15.1.4
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.3
Next.js Config:
  output: N/A
 ⚠ There is a newer version (15.1.5) available, upgrade recommended! 
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue

Node v22
 "firebase": "^10.13.2",
"next-firebase-auth-edge": "^1.8.2"

**Comment by awinogrodzki** [comment]
Hey @kcordoc,

Which browser you're using that's giving you this issue?

If you're using Chrome, you can use `CMD` + `ALT` + `I` shortcut to open Dev Tools > Application and click `Clear site data` to remove all cookies associated with the domain

<img width="1063" alt="Image" src="https://github.com/user-attachments/assets/67398496-017d-43b7-a4ea-6641e0146abe" />

That should fix the issue for you

**Comment by kcordoc** [comment]
I tried with chrome as well as Safari. Clearing site data did not fix it for me. I tried it again after your comment. 

But overall, it seems like an issue that's happening locally but not in my deployed app.

**Comment by awinogrodzki** [comment]
@kcordoc,

Could you share the error and stack trace here?

Would it be possible for you to create a repository with issue reproduction, so I can run it locally on my machine?

So far I haven't been able to reproduce this issue on my side. Having a clear way to reproduce the issue would help me address it

**Comment by kcordoc** [comment]
I just added you to my repo. 

Warning: I am far from a developer. So pardon the mess as I am learning.

**Comment by kcordoc** [comment]
Just sent it. Thanks!

**Comment by awinogrodzki** [comment]
@kcordoc, the reason for the error in your app is that you setup `/api/login` route manually in `/src/app/api/login/route.ts`

In the API route you're setting `idToken` itself as `AuthCookie`:

```tsx
    const response = new Response(JSON.stringify({ success: true }), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Set-Cookie": `${serverConfig.cookieName}=${idToken}; HttpOnly; Path=/; SameSite=Lax${process.env.NODE_ENV === "production" ? "; Secure" : ""}`,
      },
    });
```

This is incorrect, as `idToken` is not the same as `next-firebase-auth-edge` authorization cookie.

`next-firebase-auth-edge` automatically handles `/api/login` requests and you should not create your own API route.

To resolve the issue you're having follow these points:

1. You should remove `api/login/route.ts` file
2. You should move `middleware.ts` file inside `./src` dir


You Middleware is simply ignored by Next.js, because it's not inside `src` dir

**Comment by kcordoc** [comment]
Thanks a lot for looking at it!  😳 Clearly an user issue.

**Comment by awinogrodzki** [comment]
I will close the issue now as the issue seems unrelated to the library
